# Generated by Django 4.2.4 on 2023-08-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': 'Список', 'verbose_name_plural': 'Список'},
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='body',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
